// Generated by LiveScript 1.6.0
(function(){
  var colors, i$, ref$, len$, index, attrs, j$, len1$, ref1$, attr, value, make_rgba, get_color, display_line_chart, display_records_chart, display_bar_chart, run_meet, page_sidebar;
  colors = ['FF7800', 'D8005F', '589800', '015C65', 'A64E00', '8C003D', 'BCF46E', '5EC4CD', 'FFB573', 'EB6AA3', '78AF2C', '1E6D74', 'BF7330', 'A2285E', 'A7F43D', '35C0CD', 'FF9A40', 'EB3B88', '87EA00', '028E9B'];
  $.each(colors, function(index, color){
    return $(".team" + index).css("color", "black").css("background-color", "#" + color);
  });
  for (i$ = 0, len$ = (ref$ = [[['font-size', '12px'], ['text-align', 'right']], [['font-size', '12px'], ['text-align', 'right']], [['font-size', '12px'], ['text-align', 'center'], ['padding-right:10%']], [['font-size', '18px'], ['text-align', 'left']], [['font-size', '14px']], [['font-size', '14px']], [['font-size', '10px']]]).length; i$ < len$; ++i$) {
    index = i$;
    attrs = ref$[i$];
    for (j$ = 0, len1$ = attrs.length; j$ < len1$; ++j$) {
      ref1$ = attrs[j$], attr = ref1$[0], value = ref1$[1];
      $('.meet tbody tr td:nth-child(' + (index + 1) + ')').css(attr, value);
    }
  }
  $('.records tbody tr td:nth-child(1n)').css('text-align', 'center').css('border-right', '1px solid #000000').css('font-size:20px');
  for (i$ = 0, len$ = (ref$ = [[['text-align', 'left'], ['border-right:1px solid #000000']]]).length; i$ < len$; ++i$) {
    index = i$;
    attrs = ref$[i$];
    for (j$ = 0, len1$ = attrs.length; j$ < len1$; ++j$) {
      ref1$ = attrs[j$], attr = ref1$[0], value = ref1$[1];
      $('.records tbody tr td:nth-child(' + (index + 1) + ')').css(attr, value);
    }
  }
  make_rgba = function(color, alpha){
    var r, g, b;
    r = (color & 0xff0000 || 0) >> 16;
    g = (color & 0x00ff00 || 0) >> 8;
    b = (color || 0) & 0x0000ff;
    return 'rgba(' + [r, g, b, alpha].join(',') + ')';
  };
  get_color = function(index, alpha){
    return make_rgba(parseInt(colors[index], 16), alpha);
  };
  display_line_chart = function(chartData, canvas){
    var ctx;
    Chart.defaults.global.animation = false;
    Chart.defaults.Line.pointDot = false;
    Chart.defaults.Line.datasetStrokeWidth = 3;
    $.each(chartData.datasets, function(index, dataset){
      dataset.fillColor = get_color(index, 0.5);
      dataset.strokeColor = get_color(index, 0.5);
      dataset.pointColor = get_color(index, 0.5);
      dataset.pointStrokeColor = '#fff';
      dataset.pointHighlightFill = '#fff';
      return dataset.pointHighlightStroke = get_color(index, 0.5);
    });
    if (canvas.length > 0) {
      ctx = canvas.get(0).getContext('2d');
      return window.myLine = new Chart(ctx).Line(chartData, {
        responsive: true,
        datasetFill: false
      });
    }
  };
  window.display_line_chart = display_line_chart;
  window.display_meet_chart = display_line_chart;
  display_records_chart = function(chartData, canvas){
    var ctx;
    Chart.defaults.global.animation = false;
    Chart.defaults.Line.pointDot = true;
    Chart.defaults.Line.datasetStrokeWidth = 5;
    $.each(chartData.datasets, function(index, dataset){
      dataset.fillColor = get_color(index, 1);
      dataset.pointColor = get_color(index, 1);
      dataset.pointStrokeColor = '#fff';
      dataset.pointHighlightFill = '#fff';
      return dataset.pointHighlightStroke = get_color(index, 1);
    });
    if (canvas.length > 0) {
      ctx = canvas.get(0).getContext('2d');
      return window.myLine = new Chart(ctx).Line(chartData, {
        responsive: true,
        datasetFill: false,
        maintainAspectRatio: true,
        scaleOverride: true,
        scaleSteps: 12,
        scaleStepWidth: 1000,
        showLabels: false,
        datasetStroke: false
      });
    }
  };
  display_bar_chart = function(chartData, canvas){
    var ctx;
    Chart.defaults.global.animation = false;
    Chart.defaults.Line.pointDot = false;
    Chart.defaults.Line.datasetStrokeWidth = 2;
    $.each(chartData.datasets, function(index, dataset){
      dataset.fillColor = get_color(index, 1);
      dataset.strokeColor = get_color(index, 1);
      dataset.pointColor = get_color(index, 1);
      dataset.pointStrokeColor = '#fff';
      dataset.pointHighlightFill = '#fff';
      return dataset.pointHighlightStroke = get_color(index, 1);
    });
    if (canvas.length > 0) {
      ctx = canvas.get(0).getContext('2d');
      return window.myLine = new Chart(ctx).Bar(chartData, {
        responsive: true
      });
    }
  };
  window.display_bar_chart = display_bar_chart;
  window.display_chart_by_age = display_bar_chart;
  window.display_chart_by_stroke = display_bar_chart;
  window.display_records_chart = display_records_chart;
  run_meet = function(meet, table){
    return $.each(meet.events, function(index_e, event){
      table.append('<tr><td>' + event[0] + '<td></tr>');
      return $.each(event[1], function(index_r, result){
        var tr;
        tr = document.createElement('tr');
        tr.className = 'row' + index_r % 2;
        return $.each(result, function(index_e, field){
          var td;
          td = document.createElement('td');
          td.innerHTML = field;
          tr.appendChild(td);
          return table.append(tr);
        });
      });
    });
  };
  page_sidebar = $('#sidebar');
}).call(this);
